# Generated by Django 3.1.6 on 2021-06-10 21:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210610_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bt', 'Завтрак'), ('lh', 'Обед'), ('dr', 'Ужин')], max_length=8, null=True),
        ),
    ]
